- type: light
  topic: /moreillon/light-d084cb
  position:
    x: -2
    "y": 2.1
    z: 1.5
  state: "off"
- type: light
  topic: /moreillon/light-a4d3d9
  position:
    x: 2
    "y": 2.1
    z: 1.2
  state: "off"
- type: light
  topic: /moreillon/light-a4c2f0
  position:
    x: -2.5
    "y": 2.1
    z: -1.2
  state: "off"
- type: light
  topic: /moreillon/light-d13efb
  position:
    x: 0.5
    "y": 2.1
    z: -0.6
  state: "off"
- type: light
  topic: /moreillon/light-c64739
  position:
    x: 2.7
    "y": 2.1
    z: -0.8
  state: "off"
- type: light
  topic: light/bathroom
  position:
    x: 0.7
    "y": 2.1
    z: -1.8
  state: "off"
- type: light
  topic: light/toilet
  position:
    x: 2
    "y": 2.1
    z: -1.8
  state: "off"
